on:
 tags:
    - 'fedora-31-*'

name: Fedora 31

env:
  GPG_KEY_ID: 56C464BAAC421453

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    container: fedora:31
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf distro-sync -y
        dnf install -y rpmdevtools rpm-sign wget
        # dnf install -y rpmdevtools rpm-sign 'dnf-command(builddep)'
        # dnf builddep -y pkg/fedora/kernel-surface/kernel-surface.spec

    - name: Setup secureboot certificate
      env:
        SB_KEY: ${{ secrets.SURFACE_SB_KEY }}
      run: |
        cd pkg

        # Install the surface secureboot certificate
        echo "$SB_KEY" | base64 -d > fedora/kernel-surface/surface.key
        cp keys/surface.crt fedora/kernel-surface/surface.crt

    - name: Build packages
      run: |
        cd pkg/fedora/kernel-surface

        mkdir -p out/x86_64
        cd out/x86_64

        wget https://tmsp.io/fs/repos/fedora/linux-surface/f31/kernel-surface-5.3.18-2.surface.fc31.x86_64.rpm
        wget https://tmsp.io/fs/repos/fedora/linux-surface/f31/kernel-surface-devel-5.3.18-2.surface.fc31.x86_64.rpm

        # Build the .rpm packages
        # ../makerpm

    - name: Sign packages
      env:
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        cd pkg/fedora/kernel-surface/out/x86_64

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes

        # sign packages
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-31-latest
        path: pkg/fedora/kernel-surface/out/x86_64

  release:
    name: Publish release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: fedora-31-latest

      - name: Upload assets
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_BOT_TOKEN }}
          file: ./*-latest/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  repo:
    name: Update package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: fedora:31
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: StollD/repo-test
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          dnf distro-sync -y
          dnf install -y rpmdevtools gpg createrepo_c

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: fedora-31-latest

      - name: Update repository
        env:
          GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
          GIT_TAG: ${{ github.ref }}
        run: |
          cp fedora-31-latest/*.rpm fedora/f31/
          rm -r fedora-31-latest

          cd fedora/f31
          createrepo_c --xz --update --verbose .

          # Sign the updated repository
          echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes
          gpg --detach-sign --batch --no-tty -u $GPG_KEY_ID repodata/repomd.xml

          # Convert packages into references
          for pkg in $(find . -name '*.rpm'); do
            echo "$GIT_TAG/$(basename $pkg)" > $pkg.blob
            rm $pkg
          done

      - name: Commit and push
        uses: github-actions-x/commit@v2.3
        with:
          github-token: ${{ secrets.GITHUB_BOT_TOKEN }}
          push-branch: master
          commit-message: Update Fedora 31 repo
          force-add: true
          rebase: true
          files: fedora/f31/*
          name: surfacebot
          email: i.have.no.idea.what.this.is@set.to
